version: '3'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - 5000:5000
    container_name: auth-service
    networks:
      - nginx-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/my_database

  user-service:
    build:
      context: ./user-service
    ports:
      - 5001:5001
    container_name: user-service
    networks:
      - nginx-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/my_database

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost
    networks:
      - nginx-network
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./frontend
    ports: 
      - 3000:3000
    container_name: frontend
    networks:
      - nginx-network
    depends_on:
      - auth-service
      - user-service
      - mongodb
    command: ["npm", "start"]
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx-network
    depends_on:
      - auth-service
      - user-service
      - mongodb
      - frontend

networks:
  nginx-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
